Frontend:
  impl: SimpleO3
  clock_ratio: 8
  num_expected_insts: 500000
  traces: 
    - example_inst.trace

  Translation:
    impl: RandomTranslation
    max_addr: 2147483648

MemorySysten:
  impl: GenericDRAM
  clock_ratio: 3

  DRAM:
    impl: DDR5
    org: 
      # 16 GB memory, 8 Gb * 16 / 8 bits/byte = 16 GB
      preset: DDR5_8Gb_x16
      channel: 1
      rank: 2
    timing:
      preset: DDR5_3200AN
    
    Controller:
      impl: Generic
      Scheduler:
        impl: FRFCFS
      RefreshManager:
        impl: AllBank
      RowPolicy:
        impl: ClosedRowPolicy
        cap: 4
      plugins:

    AddrMapper:
    # Row Bank Rank Column Channel
      impl: RoBaRaCoCh
